//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assimentf
{
    using System;
    using System.Collections.Generic;
    
    public partial class movie
    {
        public int Id { get; set; }
        public string Names { get; set; }
        public string Category { get; set; }
        public string preducer { get; set; }
        public int years { get; set; }
        public Nullable<int> id_user { get; set; }
    
        public virtual user user { get; set; }
    }
}
